// Code generated by sqlc. DO NOT EDIT.

package models

import (
	"database/sql"
	"time"
)

type GoadminMenu struct {
	ID         int32          `json:"id"`
	ParentID   int32          `json:"parent_id"`
	Type       int32          `json:"type"`
	Order      int32          `json:"order"`
	Title      string         `json:"title"`
	Icon       string         `json:"icon"`
	Uri        string         `json:"uri"`
	Header     sql.NullString `json:"header"`
	PluginName string         `json:"plugin_name"`
	Uuid       sql.NullString `json:"uuid"`
	CreatedAt  sql.NullTime   `json:"created_at"`
	UpdatedAt  sql.NullTime   `json:"updated_at"`
}

type GoadminOperationLog struct {
	ID        int32        `json:"id"`
	UserID    int32        `json:"user_id"`
	Path      string       `json:"path"`
	Method    string       `json:"method"`
	Ip        string       `json:"ip"`
	Input     string       `json:"input"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type GoadminPermission struct {
	ID         int32          `json:"id"`
	Name       string         `json:"name"`
	Slug       string         `json:"slug"`
	HttpMethod sql.NullString `json:"http_method"`
	HttpPath   string         `json:"http_path"`
	CreatedAt  sql.NullTime   `json:"created_at"`
	UpdatedAt  sql.NullTime   `json:"updated_at"`
}

type GoadminRole struct {
	ID        int32        `json:"id"`
	Name      string       `json:"name"`
	Slug      string       `json:"slug"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type GoadminRoleMenu struct {
	RoleID    int32        `json:"role_id"`
	MenuID    int32        `json:"menu_id"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type GoadminRolePermission struct {
	RoleID       int32        `json:"role_id"`
	PermissionID int32        `json:"permission_id"`
	CreatedAt    sql.NullTime `json:"created_at"`
	UpdatedAt    sql.NullTime `json:"updated_at"`
}

type GoadminRoleUser struct {
	RoleID    int32        `json:"role_id"`
	UserID    int32        `json:"user_id"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type GoadminSession struct {
	ID        int32        `json:"id"`
	Sid       string       `json:"sid"`
	Values    string       `json:"values"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type GoadminSite struct {
	ID          int32          `json:"id"`
	Key         sql.NullString `json:"key"`
	Value       sql.NullString `json:"value"`
	Description sql.NullString `json:"description"`
	State       int32          `json:"state"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type GoadminUser struct {
	ID            int32          `json:"id"`
	Username      string         `json:"username"`
	Password      string         `json:"password"`
	Name          string         `json:"name"`
	Avatar        sql.NullString `json:"avatar"`
	RememberToken sql.NullString `json:"remember_token"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
}

type GoadminUserPermission struct {
	UserID       int32        `json:"user_id"`
	PermissionID int32        `json:"permission_id"`
	CreatedAt    sql.NullTime `json:"created_at"`
	UpdatedAt    sql.NullTime `json:"updated_at"`
}

type IrisMenu struct {
	ID     int64         `json:"id"`
	Name   string        `json:"name"`
	Path   string        `json:"path"`
	Weight sql.NullInt32 `json:"weight"`
}

type IrisPage struct {
	ID        int64     `json:"id"`
	Title     string    `json:"title"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	Slug      string    `json:"slug"`
}

type IrisPost struct {
	ID        int64     `json:"id"`
	Title     string    `json:"title"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	Views     int64     `json:"views"`
}

type IrisSite struct {
	ID        int64          `json:"id"`
	SiteName  string         `json:"site_name"`
	SiteEmail string         `json:"site_email"`
	Slogan    sql.NullString `json:"slogan"`
	Notice    sql.NullString `json:"notice"`
}

type IrisTag struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type IrisTagsPost struct {
	ID     int64 `json:"id"`
	TagID  int64 `json:"tag_id"`
	PostID int64 `json:"post_id"`
}
